/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        AButton: typeof import('@arco-design/web-vue')['Button']
        ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
        AForm: typeof import('@arco-design/web-vue')['Form']
        AFormItem: typeof import('@arco-design/web-vue')['FormItem']
        AInput: typeof import('@arco-design/web-vue')['Input']
        AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
        AOption: typeof import('@arco-design/web-vue')['Option']
        ASelect: typeof import('@arco-design/web-vue')['Select']
        ASlider: typeof import('@arco-design/web-vue')['Slider']
        ASplit: typeof import('@arco-design/web-vue')['Split']
    }
}
